[package]
name = "bchacktool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }
rust-i18n = "3.1.2"

[lib]
name = "bclib"
path = "lib/lib.rs"
